fieldLayouts:
  acf0e513-d777-4e65-932b-c357e6f525f0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d33e581b-e5c9-488b-afd0-2643003f23c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 46dc0937-252d-42b1-af90-0b9484275b6c # svg variables
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1a8f0d4-f248-4e98-add9-34c64a0cfa8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12d508d2-3246-4cc0-a641-d85f16cec7b5 # likes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b45cf50c-9399-4d3e-878e-75ebd44a7a90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55c0323f-62ef-4435-b259-81362fce0ec6 # colors
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56549dbd-4790-4229-aee3-a4420707dd63
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3ea86307-14a3-4d09-b33d-e95c764738ce
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 40f50dfd-14d2-4db4-be79-9a96710f6bc5 # artworks
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
