dateModified: 1683024489
email:
  fromEmail: maite.lejeune@student.howest.be
  fromName: ra-the-platform
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0f461aa4-2ec2-489d-b0ac-390a151969cb: Default # Default
    40f50dfd-14d2-4db4-be79-9a96710f6bc5: artworks # artworks
    79349a10-8d31-4f98-ab9a-bfc7c023bd9a: Common # Common
    d7462a5a-030b-47ef-9b31-920635c00d5c: ra-the-platform # ra-the-platform
    f038d3eb-e61c-4beb-8630-91e826953d0a: ra-the-platform # ra-the-platform
system:
  edition: pro
  live: true
  name: ra-the-platform
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
