isPublic: true
name: 'Public Schema'
scope:
  - 'sites.d7462a5a-030b-47ef-9b31-920635c00d5c:read' # ra-the-platform
  - 'sections.40f50dfd-14d2-4db4-be79-9a96710f6bc5:read' # artworks
  - 'entrytypes.0f461aa4-2ec2-489d-b0ac-390a151969cb:read' # Default
  - 'usergroups.everyone:read'
  - 'usergroups.2556b23e-96c3-43ee-818c-a56f40f0b1fd:read' # Front-end users
